In [1]:
import pandas as pd

In [3]:
df_reference = pd.read_csv(
    r"/home/gusdpaula/code-dev/MLENG_FIAP/fase_4/data/raw/loan_data.csv"
)
df_reference.head()

/tmp/ipykernel_176663/1127064401.py:1: DtypeWarning: Columns (0: id, 19: desc, 49: next_pymnt_d, 59: verification_status_joint, 118: sec_app_earliest_cr_line, 129: hardship_type, 130: hardship_reason, 131: hardship_status, 134: hardship_start_date, 135: hardship_end_date, 136: payment_plan_start_date, 139: hardship_loan_status, 145: debt_settlement_flag_date, 146: settlement_status, 147: settlement_date) have mixed types. Specify dtype option on import or set low_memory=False.
  df_reference = pd.read_csv(r'/home/gusdpaula/code-dev/MLENG_FIAP/fase_4/data/raw/loan_data.csv')

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_new = df_reference.sample(n=1000, random_state=42)  # Simulate new data

df_new.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
392949,39651438,NaN,32000.0,32000.0,32000.0,60 months,10.49,687.65,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1273506,16411620,NaN,9600.0,9600.0,9600.0,36 months,12.99,323.42,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
324024,45122316,NaN,4000.0,4000.0,4000.0,36 months,6.68,122.93,A,A3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2066630,125356772,NaN,6025.0,6025.0,6025.0,36 months,10.91,197.00,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
477199,128490686,NaN,25000.0,25000.0,25000.0,60 months,26.30,752.96,E,E5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_new["annual_inc"] = df_new["annual_inc"] * 0.7  # Simulate a drift in annual income
df_new["loan_amnt"] = df_new["loan_amnt"] * 1.3  # Simulate a drift in loan amount

In [7]:
df_new.to_json(
    r"/home/gusdpaula/code-dev/MLENG_FIAP/fase_4/data/raw/loan_data_drifted.json",
    index=False,
)